[package]
name = "rust_wifi_deauther"
version = "0.1.0"
authors = ["markrp <markrepedersen@gmail.com>"]
edition = "2018"

[dependencies]
pnet = "0.25.0"
clap = "2.33"
custom_debug_derive = "0.4.0"
derive-try-from-primitive = "0.1.0"
nom = "5.0.1"